### ISSUE TITLE
Define a set of features for v0.1

### ISSUE THREAD

**Issue by Lleutch** [7sharp9/ReQuetzal#1]
Define a set of functionality to be taken from the [syntax](https://github.com/7sharp9/ReQuetzal/blob/master/docs/syntax.md) document.
This should be the set of functionality to be implemented for milestone v0.1.

**Comment by 7sharp9** [comment]
I'll add this to the docs section.

**Comment by 7sharp9** [comment]
fixed with #c234869d9a0032b95ad3f3a8f0259f04ec565aba
